trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: mottuflow-secrets
  - name: RESOURCE_GROUP
    value: "sprint-mottuflow"
  - name: LOCATION
    value: "brazilsouth"
  - name: ACI_NAME
    value: "mottuflow-db"
  - name: ACI_APP_NAME
    value: "mottuflow-container-app"
  - name: CONTAINER_IMAGE
    value: "mysql:8.0.34"
  - name: DOCKER_REGISTRY
    value: "index.docker.io"
  - name: DOCKER_IMAGE_NAME
    value: "$(DOCKERHUB_USER)/mottuflow-app"
  - name: DOCKER_IMAGE_TAG
    value: "$(Build.BuildId)"

stages:

# --------------------- Banco de Dados ---------------------
- stage: BancoDados
  displayName: "Estágio de Provisionamento do Banco de Dados"
  jobs:
    - job: CriarMySQL
      displayName: "Criar Container MySQL"
      steps:
        - checkout: self

        - task: AzureCLI@2
          displayName: "Provisionar MySQL no ACI"
          name: ProvisarMySQL
          inputs:
            azureSubscription: "mottuflow-connection"
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              set -e

              DB_USER=$(DB_USER)
              DB_PASSWORD=$(DB_PASSWORD)
              DB_NAME=$(DB_NAME)
              DOCKER_USER=$(DOCKERHUB_USER)
              DOCKER_PASS=$(DOCKERHUB_PASSWORD)

              echo "Criando resource group..."
              az group show --name $RESOURCE_GROUP >/dev/null 2>&1 || \
              az group create --name $RESOURCE_GROUP --location $LOCATION

              echo "Verificando container MySQL..."
              if ! az container show --resource-group $RESOURCE_GROUP --name $ACI_NAME >/dev/null 2>&1; then
                echo "Criando container MySQL..."
                
                az container create \
              --resource-group $RESOURCE_GROUP \
              --name $ACI_NAME \
              --image $CONTAINER_IMAGE \
              --ports 3306 \
              --os-type Linux \
              --cpu 1 --memory 1.5 \
              --dns-name-label "${ACI_NAME}-dns-${BUILD_BUILDID}" \
              --ip-address public \
              --environment-variables MYSQL_ROOT_PASSWORD="$DB_PASSWORD" MYSQL_DATABASE="$DB_NAME" MYSQL_USER="$DB_USER" MYSQL_PASSWORD="$DB_PASSWORD" \
              --restart-policy Always \
              --registry-login-server index.docker.io \
              --registry-username $DOCKER_USER \
              --registry-password $DOCKER_PASS
              fi

              echo "Aguardando MySQL ficar disponível..."
              TIMEOUT=300
              ELAPSED=0
              MYSQL_IP=""

              while [ -z "$MYSQL_IP" ] && [ $ELAPSED -lt $TIMEOUT ]; do
                MYSQL_IP=$(az container show --resource-group $RESOURCE_GROUP --name $ACI_NAME --query ipAddress.ip -o tsv 2>/dev/null || echo "")
                if [ -z "$MYSQL_IP" ]; then
                  sleep 5
                  ELAPSED=$((ELAPSED + 5))
                  echo "Aguardando IP... ($ELAPSED/$TIMEOUT segundos)"
                fi
              done

              if [ -z "$MYSQL_IP" ]; then
                echo "Erro: Timeout ao aguardar IP do MySQL"
                exit 1
              fi

              echo "IP obtido: $MYSQL_IP"

              echo "Validando conectividade com MySQL em $MYSQL_IP..."
              RETRY=0
              while ! nc -z -w 5 $MYSQL_IP 3306 2>/dev/null && [ $RETRY -lt 60 ]; do
                echo "Tentativa $((RETRY + 1))/60 - MySQL não está respondendo ainda..."
                sleep 5
                RETRY=$((RETRY + 1))
              done

              if [ $RETRY -eq 60 ]; then
                echo "Erro: MySQL não respondeu após 5 minutos"
                exit 1
              fi

              echo "MySQL pronto em $MYSQL_IP:3306"
              echo "##vso[task.setvariable variable=MYSQL_IP;isOutput=true]$MYSQL_IP"

# --------------------- Build e Testes ---------------------
- stage: BuildAndTest
  displayName: "Build e Testes"
  dependsOn: BancoDados
  variables:
    MYSQL_IP: $[ stageDependencies.BancoDados.CriarMySQL.outputs['ProvisarMySQL.MYSQL_IP'] ]
  jobs:
    - job: BuildTestApp
      displayName: "Build e Testes da Aplicação"
      steps:
        - checkout: self

        - task: JavaToolInstaller@0
          displayName: "Instalar Java 21"
          inputs:
            versionSpec: "21"
            jdkArchitectureOption: "x64"
            jdkSourceOption: "PreInstalled"

        - task: Maven@4
          displayName: "Build Maven com Testes"
          env:
            DB_HOST: $(MYSQL_IP)
            DB_PORT: "3306"
            DB_NAME: $(DB_NAME)
            DB_USER: $(DB_USER)
            DB_PASSWORD: $(DB_PASSWORD)
            SERVER_PORT: "8080"
          inputs:
            mavenPomFile: "MottuFlow/pom.xml"
            goals: "clean package -B"

        - task: CopyFiles@2
          displayName: "Copiar JAR para artefato"
          inputs:
            SourceFolder: "$(System.DefaultWorkingDirectory)/MottuFlow/target"
            Contents: "*.jar"
            TargetFolder: "$(Build.ArtifactStagingDirectory)"

        - publish: $(Build.ArtifactStagingDirectory)
          artifact: aplicacao
          displayName: "Publicar artefato JAR"

# --------------------- Build Docker e Push ---------------------
- stage: BuildDocker
  displayName: "Build Docker e Push"
  dependsOn: BuildAndTest
  jobs:
    - job: BuildPushDocker
      displayName: "Build e Push da Imagem Docker"
      steps:
        - checkout: self

        - task: Docker@2
          displayName: "Build Docker Image"
          inputs:
            command: build
            Dockerfile: "MottuFlow/Dockerfile"
            repository: "$(DOCKER_IMAGE_NAME)"
            tags: |
              $(DOCKER_IMAGE_TAG)
              latest
            arguments: "--build-arg BUILDKIT_INLINE_CACHE=1"

        - task: Docker@2
          displayName: "Login Docker Hub"
          inputs:
            command: login
            containerRegistry: dockerhubConnection

        - task: Docker@2
          displayName: "Push Docker Image"
          inputs:
            command: push
            repository: "$(DOCKER_IMAGE_NAME)"
            tags: |
              $(DOCKER_IMAGE_TAG)
              latest

# --------------------- Deploy em ACI ---------------------
- stage: Deploy
  dependsOn: 
    - BancoDados
    - BuildDocker
  displayName: "Deploy em Azure Container Instance"
  variables:
    MYSQL_IP: $[ stageDependencies.BancoDados.CriarMySQL.outputs['ProvisarMySQL.MYSQL_IP'] ]
  jobs:
    - job: DeployACI
      displayName: "Deployar Aplicação em ACI"
      steps:
        - checkout: none

        - task: AzureCLI@2
          displayName: "Deploy Aplicação em ACI"
          inputs:
            azureSubscription: "mottuflow-connection"
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              set -e

              DOCKER_USER=$(DOCKERHUB_USER)
              DOCKER_PASS=$(DOCKERHUB_PASSWORD)
              DB_PASSWORD=$(DB_PASSWORD)

              echo "Iniciando deploy da aplicação em ACI..."
              echo "MySQL IP: $(MYSQL_IP)"
              echo "Imagem Docker: $(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG)"

              if [ -z "$(MYSQL_IP)" ]; then
                echo "Erro: MYSQL_IP não foi definido!"
                exit 1
              fi

              az container delete \
                --resource-group $(RESOURCE_GROUP) \
                --name $(ACI_APP_NAME) \
                --yes >/dev/null 2>&1 || echo "Nenhum container anterior para remover"

              sleep 5

              az container create \
                --resource-group $(RESOURCE_GROUP) \
                --name $(ACI_APP_NAME) \
                --image "$(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG)" \
                --ports 8080 \
                --os-type Linux \
                --cpu 1 --memory 1.5 \
                --dns-name-label "mottuflow-app" \
                --ip-address public \
                --environment-variables \
                  DB_HOST="$(MYSQL_IP)" \
                  DB_PORT="3306" \
                  DB_NAME="$(DB_NAME)" \
                  DB_USER="$(DB_USER)" \
                  DB_PASSWORD="$DB_PASSWORD" \
                  SERVER_PORT="8080" \
                --restart-policy Always \
                --registry-login-server $(DOCKER_REGISTRY) \
                --registry-username $DOCKER_USER \
                --registry-password $DOCKER_PASS

              echo "Aguardando container ficar pronto..."
              sleep 10

              APP_FQDN=$(az container show --resource-group $(RESOURCE_GROUP) --name $(ACI_APP_NAME) --query ipAddress.fqdn -o tsv)
              echo "✅ Aplicação deployada com sucesso!"
              echo "🌐 URL: http://$APP_FQDN:8080"