trigger:
  branches:
    include:
      - main

pool:
  name: pool-mottuflow

stages:
# --------------------- CI ---------------------
- stage: Build_Test
  displayName: 'CI - Build e Testes'
  jobs:
  - job: Build
    steps:
    - checkout: self

    - task: Maven@4
      displayName: 'Build e Testes com Maven'
      inputs:
        mavenPomFile: 'MottuFlow/pom.xml'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'

    - task: PublishBuildArtifacts@1
      displayName: 'Publicar artefato Maven'
      inputs:
        PathtoPublish: 'MottuFlow/target'
        ArtifactName: 'mottuflow'
        publishLocation: 'Container'

# --------------------- CD ---------------------
- stage: Deploy
  displayName: 'CD - Deploy no ACI'
  dependsOn: Build_Test
  condition: succeeded()
  jobs:
  - job: DeployJob
    steps:
    - checkout: self

    - task: DownloadBuildArtifacts@1
      displayName: 'Baixar artefato'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'mottuflow'
        downloadPath: '$(Pipeline.Workspace)/artifact'

    - task: AzureCLI@2
      displayName: 'Build e push da imagem para o ACR'
      inputs:
        azureSubscription: 'mottuflow-connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          cd MottuFlow
          chmod +x build.sh
          ./build.sh

    - task: AzureCLI@2
      displayName: 'Deploy no ACI'
      inputs:
        azureSubscription: 'mottuflow-connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          cd MottuFlow
          chmod +x deploy.sh
          ./deploy.sh
      env:
        DB_USER: $(DB_USER)
        DB_PASSWORD: $(DB_PASSWORD)
