trigger:
  branches:
    include:
      - main


pool:
  name: pool-mottuflow

stages:
# --------------------- CI (Build) ---------------------
- stage: Build
  displayName: 'CI - Build'
  jobs:
  - job: BuildJob
    displayName: 'Job de Build'
    steps:
    - checkout: self

    - task: Maven@4
      displayName: 'Build com Maven'
      inputs:
        mavenPomFile: 'MottuFlow/pom.xml'
        goals: 'clean package -DskipTests=true'
        publishJUnitResults: false

    - task: PublishBuildArtifacts@1
      displayName: 'Publicar artefato Maven'
      inputs:
        PathtoPublish: 'MottuFlow/target'
        ArtifactName: 'mottuflow'
        publishLocation: 'Container'

# --------------------- CD (Deploy) ---------------------
- stage: Deploy
  displayName: 'CD - Deploy no Azure Web App e Testes'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeployJob
    displayName: 'Job de Deploy'
    steps:
    - checkout: self

    # Baixa os artefatos gerados no Build
    - task: DownloadBuildArtifacts@1
      displayName: 'Baixar artefato'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'mottuflow'
        downloadPath: '$(Pipeline.Workspace)/artifact'

    - task: AzureCLI@2
      displayName: 'Criar Web App (se necessário)'
      inputs:
        azureSubscription: 'mottuflow-connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          cd MottuFlow
          chmod +x webapp.sh
          ./webapp.sh

    - task: AzureWebApp@1
      displayName: 'Deploy no Azure Web App'
      inputs:
        azureSubscription: 'mottuflow-connection'
        appType: 'webAppLinux'
        appName: 'mottuflow-app'
        package: '$(Pipeline.Workspace)/artifact/mottuflow/*.jar'

    - task: Maven@4
      displayName: 'Testes de integração'
      inputs:
        mavenPomFile: 'MottuFlow/pom.xml'
        goals: 'test'
        options: '-Dspring.profiles.active=dev'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
