trigger:
  branches:
    include:
      - main

pool:
  name: pool-mottuflow

stages:
# --------------------- CI ---------------------
- stage: Build
  displayName: 'CI - Build'
  jobs:
  - job: BuildJob
    steps:
    - checkout: self

    - task: Maven@4
      displayName: 'Build com Maven'
      inputs:
        mavenPomFile: 'MottuFlow/pom.xml'
        goals: 'clean package -DskipTests=true'
        publishJUnitResults: false

    - task: PublishBuildArtifacts@1
      displayName: 'Publicar artefato Maven'
      inputs:
        PathtoPublish: 'MottuFlow/target'
        ArtifactName: 'mottuflow'
        publishLocation: 'Container'

# --------------------- CD ---------------------
- stage: Deploy
  displayName: 'CD - Deploy Web App + Banco'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeployJob
    steps:
    - checkout: self

    - task: DownloadBuildArtifacts@1
      displayName: 'Baixar artefato'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'mottuflow'
        downloadPath: '$(Pipeline.Workspace)/artifact'

    - task: AzureCLI@2
      displayName: 'Criar Web App, DB e ACR'
      inputs:
        azureSubscription: 'mottuflow-connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          cd MottuFlow
          chmod +x webapp.sh
          ./webapp.sh
      env:
        DB_USER: $(DB_USER)
        DB_PASS: $(DB_PASSWORD)

  - task: Maven@4
    displayName: 'Testes de integração com DB'
    inputs:
      mavenPomFile: 'MottuFlow/pom.xml'
      goals: 'test'
      options: '-Dspring.profiles.active=dev'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
    env:
      DB_HOST: $(DB_IP)
      DB_PORT: 3306
      DB_USER: $(DB_USER)
      DB_PASSWORD: $(DB_PASSWORD)