trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  DB_USER: "mottuuser"
  DB_PASSWORD: "MottuPass123!"
  DB_NAME: "mottuflow"
  RESOURCE_GROUP: "sprint-mottuflow"
  WEBAPP_NAME: "mottuflow-app"
  APP_PLAN: "mottuflow-plan"
  LOCATION: "brazilsouth"
  ACI_NAME: "mottuflow-db"
  CONTAINER_IMAGE: "mysql:8.0"

stages:

# --------------------- Build ---------------------
- stage: Build
  displayName: "Build stage"
  jobs:
    - job: Build
      displayName: "Build job"
      container: maven:3.9.11-eclipse-temurin-21-noble
      steps:
        - checkout: self

        - task: Maven@4
          displayName: "Build com Maven"
          inputs:
            mavenPomFile: "MottuFlow/pom.xml"
            goals: "clean package -DskipTests=true"
            publishJUnitResults: true
            testResultsFiles: "**/surefire-reports/TEST-*.xml"

        - task: CopyFiles@2
          displayName: "Copy Files to artifact staging directory"
          inputs:
            SourceFolder: "$(System.DefaultWorkingDirectory)"
            Contents: "**/target/*.jar"
            TargetFolder: $(Build.ArtifactStagingDirectory)

        - publish: $(Build.ArtifactStagingDirectory)
          artifact: demo

# --------------------- MySQL ACI ---------------------
- stage: MySQL
  displayName: "Create MySQL ACI"
  dependsOn: Build
  jobs:
    - job: CreateACI
      displayName: "Provision MySQL container"
      steps:
        - task: AzureCLI@2
          displayName: "Criar ACI MySQL"
          inputs:
            azureSubscription: "mottuflow-connection"
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az group show --name $RESOURCE_GROUP >/dev/null 2>&1 || \
              az group create --name $RESOURCE_GROUP --location $LOCATION

              # Cria o container se não existir
              az container show --resource-group $RESOURCE_GROUP --name $ACI_NAME >/dev/null 2>&1 || \
              az container create \
                --resource-group $RESOURCE_GROUP \
                --name $ACI_NAME \
                --image $CONTAINER_IMAGE \
                --ports 3306 \
                --cpu 1 \
                --memory 1.5 \
                --dns-name-label "${ACI_NAME}-dns-${BUILD_BUILDID}" \
                --ip-address public \
                --environment-variables \
                    MYSQL_ROOT_PASSWORD="$DB_PASSWORD" \
                    MYSQL_DATABASE="$DB_NAME" \
                    MYSQL_USER="$DB_USER" \
                    MYSQL_PASSWORD="$DB_PASSWORD" \
                --restart-policy Always

              # Espera o MySQL ficar pronto
              echo "Aguardando MySQL em execução..."
              DB_IP=""
              while [ -z "$DB_IP" ]; do
                DB_IP=$(az container show --resource-group $RESOURCE_GROUP --name $ACI_NAME --query ipAddress.ip -o tsv)
                [ -z "$DB_IP" ] && sleep 5
              done
              echo "MySQL pronto em $DB_IP"

              # Define variável de pipeline para usar no deploy
              echo "##vso[task.setvariable variable=DB_IP]$DB_IP"

# --------------------- Deploy ---------------------
- stage: Deploy
  displayName: "Deploy Web App"
  dependsOn: MySQL
  condition: succeeded()
  jobs:
    - deployment: DeployWebApp
      displayName: "Deploy Web App"
      environment: "Production"
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self

              # Deploy do artifact
              - task: AzureWebApp@1
                displayName: "Deploy to Azure Web App"
                inputs:
                  azureSubscription: "mottuflow-connection"
                  appType: "webAppLinux"
                  appName: "$(WEBAPP_NAME)"
                  package: "$(Pipeline.Workspace)/demo/target/*.jar"

              - task: AzureCLI@2
                displayName: "Set DB settings in Web App"
                inputs:
                  azureSubscription: "mottuflow-connection"
                  scriptType: bash
                  scriptLocation: inlineScript
                  inlineScript: |
                    az webapp config appsettings set \
                      --name $WEBAPP_NAME \
                      --resource-group $RESOURCE_GROUP \
                      --settings DB_HOST=$(DB_IP) DB_PORT=3306 DB_NAME=$DB_NAME DB_USER=$DB_USER DB_PASSWORD=$DB_PASSWORD
