trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: mottuflow-secrets
  - name: RESOURCE_GROUP
    value: "sprint-mottuflow"
  - name: WEBAPP_NAME
    value: "mottuflow-app"
  - name: APP_PLAN
    value: "mottuflow-plan"
  - name: LOCATION
    value: "brazilsouth"
  - name: ACI_NAME
    value: "mottuflow-db"
  - name: CONTAINER_IMAGE
    value: "mysql:8.0.34"

stages:

# --------------------- Build ---------------------
- stage: Build
  displayName: "Build"
  jobs:
    - job: BuildApp
      container: maven:3.9.11-eclipse-temurin-21-noble
      steps:
        - checkout: self

        - task: Maven@4
          displayName: "Build Maven"
          inputs:
            mavenPomFile: "MottuFlow/pom.xml"
            goals: "clean package -DskipTests=true"

        - task: CopyFiles@2
          displayName: "Copiar JAR para artefato"
          inputs:
            SourceFolder: "$(System.DefaultWorkingDirectory)/MottuFlow/target"
            Contents: "*.jar"
            TargetFolder: "$(Build.ArtifactStagingDirectory)"

        - publish: $(Build.ArtifactStagingDirectory)
          artifact: demo
          displayName: "Publicar artefato JAR"

# --------------------- Banco de Dados ---------------------
- stage: BancoDados
  displayName: "Estágio de Provisionamento do Banco de Dados"
  dependsOn: Build
  jobs:
    - job: CriarMySQL
      displayName: "Criar Container MySQL"
      steps:
        - checkout: self

        - task: AzureCLI@2
          displayName: "Provisionar MySQL no ACI"
          name: ProvisarMySQL
          inputs:
            azureSubscription: "mottuflow-connection"
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              set -e

              DB_USER=$(DB_USER)
              DB_PASSWORD=$(DB_PASSWORD)
              DB_NAME=$(DB_NAME)

              DOCKER_USER=$(DOCKERHUB_USER)
              DOCKER_PASS=$(DOCKERHUB_PASSWORD)

              echo "Criando resource group..."
              az group show --name $RESOURCE_GROUP >/dev/null 2>&1 || \
              az group create --name $RESOURCE_GROUP --location $LOCATION

              echo "Verificando container MySQL..."
              if ! az container show --resource-group $RESOURCE_GROUP --name $ACI_NAME >/dev/null 2>&1; then
                echo "Criando container MySQL..."
                
                az container create \
              --resource-group $RESOURCE_GROUP \
              --name $ACI_NAME \
              --image $CONTAINER_IMAGE \
              --ports 3306 \
              --os-type Linux \
              --cpu 1 --memory 1.5 \
              --dns-name-label "${ACI_NAME}-dns-${BUILD_BUILDID}" \
              --ip-address public \
              --environment-variables MYSQL_ROOT_PASSWORD="$DB_PASSWORD" MYSQL_DATABASE="$DB_NAME" MYSQL_USER="$DB_USER" MYSQL_PASSWORD="$DB_PASSWORD" \
              --restart-policy Always \
              --registry-login-server index.docker.io \
              --registry-username $DOCKER_USER \
              --registry-password $DOCKER_PASS
              fi

              echo "Aguardando MySQL ficar disponível..."
              TIMEOUT=300
              ELAPSED=0
              DB_IP=""

              while [ -z "$DB_IP" ] && [ $ELAPSED -lt $TIMEOUT ]; do
                DB_IP=$(az container show --resource-group $RESOURCE_GROUP --name $ACI_NAME --query ipAddress.ip -o tsv 2>/dev/null || echo "")
                if [ -z "$DB_IP" ]; then
                  sleep 5
                  ELAPSED=$((ELAPSED + 5))
                  echo "Aguardando IP... ($ELAPSED/$TIMEOUT segundos)"
                fi
              done

              if [ -z "$DB_IP" ]; then
                echo "Erro: Timeout ao aguardar IP do MySQL"
                exit 1
              fi

              echo "IP obtido: $DB_IP"

              echo "Validando conectividade com MySQL em $DB_IP..."
              RETRY=0
              while ! nc -z -w 5 $DB_IP 3306 2>/dev/null && [ $RETRY -lt 60 ]; do
                echo "Tentativa $((RETRY + 1))/60 - MySQL não está respondendo ainda..."
                sleep 5
                RETRY=$((RETRY + 1))
              done

              if [ $RETRY -eq 60 ]; then
                echo "Erro: MySQL não respondeu após 5 minutos"
                exit 1
              fi

              echo "MySQL pronto em $DB_IP:3306"
              
              echo "##vso[task.setvariable variable=DB_IP;isOutput=true]$DB_IP"
              echo "DB_IP setada como output: $DB_IP"

# --------------------- Deploy ---------------------
- stage: Deploy
  dependsOn: BancoDados
  displayName: "Deploy"
  variables:
    DB_IP: $[ stageDependencies.BancoDados.CriarMySQL.outputs['CriarMySQL.DB_IP'] ]
  jobs:
    - job: DeployApp
      steps:
        - checkout: none

        - task: AzureCLI@2
          displayName: "Validar DB_IP"
          inputs:
            azureSubscription: "mottuflow-connection"
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              echo "Validando DB_IP recebida: $(DB_IP)"
              if [ -z "$(DB_IP)" ]; then
                echo "Erro: DB_IP está vazia!"
                exit 1
              fi
              echo "DB_IP validada com sucesso: $(DB_IP)"

        - task: AzureCLI@2
          displayName: "Configurar WebApp e Variáveis"
          inputs:
            azureSubscription: "mottuflow-connection"
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              set -e

              DB_IP_VALUE=$(DB_IP)
              echo "DB_IP recebida: $DB_IP_VALUE"
              
              if [ -z "$DB_IP_VALUE" ]; then
                echo "Recuperando DB_IP do ACI..."
                DB_IP_VALUE=$(az container show --resource-group $(RESOURCE_GROUP) --name $(ACI_NAME) --query ipAddress.ip -o tsv)
                echo "DB_IP recuperada: $DB_IP_VALUE"
              fi

              if [ -z "$DB_IP_VALUE" ]; then
                echo "Erro crítico: Não foi possível obter DB_IP"
                exit 1
              fi

              echo "Iniciando configuração do WebApp..."
              echo "DB_IP recebida: $DB_IP_VALUE"
              echo "Resource Group: $(RESOURCE_GROUP)"
              echo "WebApp: $(WEBAPP_NAME)"
              echo "Plano: $(APP_PLAN)"

              echo "Verificando plano de serviço..."
              az appservice plan show -n $(APP_PLAN) -g $(RESOURCE_GROUP) >/dev/null 2>&1 || \
              az appservice plan create -n $(APP_PLAN) -g $(RESOURCE_GROUP) --sku B1 --is-linux -l $(LOCATION)

              echo "Verificando aplicação web..."
              if ! az webapp show -n $(WEBAPP_NAME) -g $(RESOURCE_GROUP) >/dev/null 2>&1; then
                echo "Criando nova aplicação web..."
                az webapp create -n $(WEBAPP_NAME) -g $(RESOURCE_GROUP) -p $(APP_PLAN) --runtime "JAVA|21-java21"
              else
                echo "Aplicação já existe. Atualizando variáveis..."
              fi

              echo "Aplicando variáveis de ambiente..."
              az webapp config appsettings set \
                -n $(WEBAPP_NAME) \
                -g $(RESOURCE_GROUP) \
                --settings \
                  DB_HOST="$DB_IP_VALUE" \
                  DB_PORT="3306" \
                  DB_NAME="$(DB_NAME)" \
                  DB_USER="$(DB_USER)" \
                  DB_PASSWORD="$(DB_PASSWORD)" \
                  JAVA_OPTS="-Xmx768M -Xms512M -XX:+TieredCompilation -XX:TieredStopAtLevel=4" \
                  SERVER_COMPRESSION_ENABLED="true"

              echo "Configuração de ambiente concluída com sucesso."
              echo "Listando variáveis configuradas:"
              az webapp config appsettings list -n $(WEBAPP_NAME) -g $(RESOURCE_GROUP)

        - download: current
          artifact: demo

        - task: AzureWebApp@1
          displayName: "Implantar JAR no WebApp"
          inputs:
            azureSubscription: "mottuflow-connection"
            appType: "webAppLinux"
            appName: "$(WEBAPP_NAME)"
            package: "$(Pipeline.Workspace)/demo/*.jar"
            deploymentMethod: runFromPackage
